### ISSUE TITLE
Allow removal of icons

### ISSUE THREAD

**Issue by grahamperrin** [charles-m-knox/firefox-containers-helper#13]
For use cases such as mine, most icons are a waste of space: 

![image](https://user-images.githubusercontent.com/192271/111715142-1d464000-884b-11eb-8ddd-1054107333ee.png)

* no sense in forcing me to choose an icon for `gjp4`, and so on. 

I want to remove all icons. 

Other users might prefer to remove just some icons. 

Realistically, it might be difficult (or impossible) to 'close' the space formerly occupied by an icon – see for example https://github.com/mozilla/multi-account-containers/issues/771#issuecomment-333893217 – so I'll be happy with simple removal of icons. 

(The dead space will be slightly wasteful, but not troublesome.)

**Comment by charles-m-knox** [comment]
I understand where you're coming from on this. I think the containers API actually *requires* an icon and color to be set, or else it refuses to create a container entirely. I have to confirm this, but if my suspicion is correct, then it's 100% impossible for me to do anything about it.

However, I could add a user preference to hide/show the icons in the Containers Helper addon popup window, that would be about as close as I could get to this. What do you think @grahamperrin?

**Comment by grahamperrin** [comment]
Thanks, 

> … a user preference to hide/show the icons in the Containers Helper addon popup window, …

In that (rarely seen) context, icons don't bother me. 

The near-omnipresent address bar context is where I'd like to be without icons. 

In the absence of an API, this is probably _cantfix_. 

Certainly, when I disposed of icons, it required manual edition of `containers.js` …

**Comment by charles-m-knox** [comment]
Gotcha. I agree with your assessment and will tag as cantfix and close.
