### ISSUE TITLE
Use non-localised links to AMO

### ISSUE THREAD

**Issue by grahamperrin** [charles-m-knox/firefox-containers-helper#14]
At the front page https://github.com/charles-m-knox/firefox-containers-helper

* in lieu of https://addons.mozilla.org/en-US/firefox/addon/containers-helper
* https://addons.mozilla.org/addon/containers-helper

**Comment by charles-m-knox** [comment]
Thank you for pointing this out. I can definitely include this in the next update.

**Comment by grahamperrin** [comment]
Thanks!
