### ISSUE TITLE
Managing Which URLs Containers Apply To

### ISSUE THREAD

**Issue by ReticentAdjuvant** [charles-m-knox/firefox-containers-helper#2]
My biggest disappointment with the native containers addon is not being able to manage how containers are applied. 

This means...
A. being able to use the UI to add one URL after the other in succession (something that is currently impossible) and...
B. not being required to put every single subdomain in the list to make a domain consistently appear in a container.

A: Currently, if I want to add multiple URLs to a container I have to open a tab, go to the URL, right-click, Always Open This Site in, close the tab, open a new tab, go to the URL and confirm that I want it to continue opening it in its designated container, And start the process all over again for each subsequent URL. _<breaks pencil>_

B: It gets better. If I want a domain with many subdomains to consistently open in a container I have to hunt for all of its subdomains and do this process for every...single...one of them. _<flips table with Slashdot open on the screen>_

All I need is a text box and an asterisk. 

Slashdot Container >> *://*.slashdot.org* >> BAM. Done.

Is this within the realms of this addon? I know It's more about having many containers but I figured I'd ask.

**Comment by charles-m-knox** [comment]
I feel your pain on this one. Currently, the containers helper addon doesn't actually even touch the MAC addon's configuration for automatically opening URL's in containers.

I tried looking into the MAC addon's source code to see how I could modify the automatic URLs for containers, and was unsuccessful. However, I've since been sent one or two extensions that seem to be able to reconfigure those settings.

@ReticentAdjuvant , have you seen the Containerise extension? https://github.com/kintesh/containerise - I don't use this addon yet, I may try it in the future - but it looks to me like both Containerise and Containers Helper will play very well together.

Please let me know if this addon does what you want! It would be good to hear back from you.

**Comment by KerfuffleV2** [comment]
@charles-m-knox Not the same person but I was also recently trying to figure out how to get around multi-account-containers' horrendous UI and lack of ability to actually add hosts. Unfortunately, it's actually impossible to interface with MAC to change its configuration. 

It has a bunch of messages it can receive internally: https://github.com/mozilla/multi-account-containers/blob/f0afc0da36d8bd217ef5db89c39f04cb0e27379d/src/js/background/messageHandler.js

However, there is only other message it supports from other addons with is `getAssignment`: https://github.com/mozilla/multi-account-containers/blob/f0afc0da36d8bd217ef5db89c39f04cb0e27379d/src/js/background/messageHandler.js#L126

This is what the temporary-containers addon (and possibly others?) uses to interface with MAC.

I actually figured out how to manually add a site entry to MAC's configuration via the `about:debugging` interface and editing its extension storage. However, the process is certainly not user friendly and as far as I'm aware there's no way for one addon to access another addon's storage (except by messaging like `getAssignment` but it would have to be explicitly handled by that addon.)

Other addons that work with containers and associated URIs like Containerise are just doing their own configuration and handling of that feature completely independently.

**Comment by charles-m-knox** [comment]
Hey @KerfuffleV2, thanks for sharing your findings on this. I'm relieved to not be the only one who was unsuccessful here, but also a bit sad that it seems we won't be able to modify those settings. It seems that for now, we may want to just have containerise and containers helper working in concert.
