### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by grahamperrin** [charles-m-knox/firefox-containers-helper#24]
I found the notes at https://github.com/charles-m-knox/firefox-containers-helper/releases (thanks) however it will be nice to also have the notes traditionally visible: 

* within the extension, i.e. in the tab when the extension is viewed at about:addons
* at AMO, i.e. https://addons.mozilla.org/en-GB/firefox/addon/containers-helper/versions/0.0.18/updateinfo/ and https://addons.mozilla.org/en-GB/firefox/addon/containers-helper/versions/

Thanks

**Comment by charles-m-knox** [comment]
Hey @grahamperrin, thanks for pointing this out. I wasn't aware of this actually, but going forward, now I know how to do it : )

I updated the version info with the information from the GitHub release: https://addons.mozilla.org/en-GB/firefox/addon/containers-helper/versions/0.0.18/updateinfo/ - I'll also do this for future releases as well.

As for the actual description in `about:addons`, it looks like that's the same content that's displayed on the AMO description. When I do the next release, I'll make a couple updates include something like a "Latest Changes" section in the description.

I hope you're enjoying the extension! :slightly_smiling_face:

**Comment by grahamperrin** [comment]
Thanks! 

https://addons.mozilla.org/en-GB/firefox/addon/containers-helper/reviews/1683353/

As a comparison, about:addons views of things: 

![image](https://user-images.githubusercontent.com/192271/128985841-8ce52664-d9a6-4e71-a303-65365c5d6a74.png)

* a _Release Notes_ tab

![image](https://user-images.githubusercontent.com/192271/128989592-fbe91f46-9a8e-4028-b3b4-1e2cadc13a30.png)

* no tab. 

I guess, there's a standard way of building in the tab, then (yes) it presents the localised update info.

**Comment by charles-m-knox** [comment]
I see what you mean! I'm looking into it...

**Comment by charles-m-knox** [comment]
I _think_ I just need to set the release notes when the extension gets released via AMO. I'll keep this issue open - next time I do a release, I will test out my theory and report back here.

**Comment by charles-m-knox** [comment]
@grahamperrin Think I figured out how to set the release notes... I had to do this via the AMO website, I still need to figure out how to set release notes via Mozilla's `web-ext` tool, which I prefer to use for publishing new releases. If you happen to know a way... I'm all ears!

In the mean time, here's how it looks:

![Screenshot-20210912133609-635x281](https://user-images.githubusercontent.com/8022749/133002029-8ce20e26-983a-4fef-86f5-b42eed0cf0f3.png)

Thanks : )
