### ISSUE TITLE
If current tab site domain name matches container default URL, reopen current URL?

### ISSUE THREAD

**Issue by erwin** [charles-m-knox/firefox-containers-helper#29]
If the tab that I currently have open in Firefox is:

https://github.com/charles-m-knox/firefox-containers-helper/issues

And I click the "Containers Helper" dropdown, and choose a container where the default URL is "github.com", could we use the Current Selected tab URL as the URL to open?

Let's say in my Firefox Containers Helper's list I have:

- home - default url: github.com
- work - default url: github.com

If the current tab is also github.com, it would be nice to load the entire current URL in the new tab (that's inside of a container).

Please consider.

**Comment by charles-m-knox** [comment]
@erwin thanks for the suggestion! It should be doable. I won't be able to implement it for a couple days I think, but I will plan to.

I suspect I won't make it the default behavior, but definitely a feature you can configure to enable. I'll post an update here when I make progress on this.

**Comment by charles-m-knox** [comment]
@erwin This has been implemented in the `main` branch. It will be released hopefully soon, assuming it tests well on my personal system.

**Comment by charles-m-knox** [comment]
@erwin v0.0.22 has been released, which contains your requested feature!

https://addons.mozilla.org/en-US/firefox/addon/containers-helper/

Let me know if you run into any issues.

**Comment by erwin** [comment]
Thank you Charles! That works great!!!

![image](https://user-images.githubusercontent.com/11534217/134830029-d6778adf-7e65-47c2-abce-801350a774d6.png)

**Comment by charles-m-knox** [comment]
Hooray!
