### ISSUE TITLE
Make the Keyboard Shortcut to open the Popup Window Configurable

### ISSUE THREAD

**Issue by mrzzy** [charles-m-knox/firefox-containers-helper#4]
### The Issue
The Keyboard Shortcut to open the Popup Window is `Alt+Shift+D`
- This conflicts with another extension I have installed:   
   [Dark Reader](https://darkreader.org/) which uses `Alt+Shift+D` to toggle the dark mode generated by the extension on/off.

### Proposal
Make the Keyboard Shortcut to open the Popup Window Configurable
- Allows users to prevent conflicts between extensions.

Hats off to your effort on this extension :+1:

**Comment by charles-m-knox** [comment]
I am sorry this conflicts with dark mode (and possibly other people's shortcuts)! I will work on making the shortcut configurable in my next update. Thank you for taking the time to provide feedback. Enjoy the extension in the mean time!

**Comment by charles-m-knox** [comment]
Note to self for later: When implementing this, make sure to update references to alt+shift+D in the readme/docs/any where else aside from the code itself.

**Comment by charles-m-knox** [comment]
https://github.com/mdn/webextensions-examples/tree/60ce50b10ee66f6d706b0715909e756e4bdba63d/commands

For my reference.

**Comment by charles-m-knox** [comment]
![keyboard_shortcuts_dark](https://user-images.githubusercontent.com/8022749/111537260-76698300-8728-11eb-81dd-3adf5569d1a1.png)
![keyboard_shortcuts_light](https://user-images.githubusercontent.com/8022749/111537262-77021980-8728-11eb-9b9c-7307c410ad87.png)

Work in progress. Appears to be fully functional on my local branch. Doing some polishing now.

**Comment by charles-m-knox** [comment]
![image](https://user-images.githubusercontent.com/8022749/111537444-ae70c600-8728-11eb-8b6d-abfe297e0afd.png)

Here's how it appears, with a bit more context. Notice that it respects dark mode now, too, thanks to #8.

**Comment by charles-m-knox** [comment]
The next release will include this update.

**Comment by mrzzy** [comment]
Thanks @charles-m-knox for hard work to bring this feature to reality :tada:. Much appreciated :pray:.

**Comment by charles-m-knox** [comment]
You're welcome @mrzzy!
