### ISSUE TITLE
Please consider respecting dark theme preference

### ISSUE THREAD

**Issue by KerfuffleV2** [charles-m-knox/firefox-containers-helper#5]
It should be pretty simple using the `prefers-color-scheme` media selector: 
```css
@media (prefers-color-scheme: dark) { /* ... */ }
```

[Here's an example](https://github.com/mozilla/multi-account-containers/blob/682d877960ced0826d1a8def540bdd5e252b9192/src/css/options.css) of it being used in the official multi-account-containers addon CSS.

**Comment by charles-m-knox** [comment]
Hi @KerfuffleV2 , thanks for providing your feedback on the extension. I will work on including dark mode in my next update.

I appreciate you helping me out with providing the CSS selector too, that will help me implement this feature request - any more code snippets you happen to have on hand will greatly help me expedite the implementation!

**Comment by KerfuffleV2** [comment]
@charles-m-knox Thanks for the quick reply! I'm not much of an expert on CSS or Firefox addons but I can include a little more information that might be useful:

Here's a link to Mozilla's page on that selector: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

The approach used by the addon I linked seemed to be to define the normal light-mode CSS and then override some values specifically for people that prefer a dark scheme. I would guess this is probably the easiest way to do it - in that case your `prefers-dark-scheme` part would need to occur after the normal definitions.

You can create `ui.systemUsesDarkTheme` key in `about:config` with the number type. If set to `0` it will force a light scheme, if `1` a dark scheme and changing it takes effect immediately. Also if `privacy.resistFingerprinting` is set to `true` then unfortunately a dark scheme isn't respected for sites _or_ addons and the only way around that would be to create an actual setting in your addon to toggle dark mode.

I hope that's helpful! If you end up having any specific problems or questions with it I might be able to help more.

**Comment by charles-m-knox** [comment]
Thank you! Much appreciated.
